config/routes.rb
Rails.application.routes.draw do
  root to: 'root#index'
  resources :root
  namespace :api do
    namespace :v0 do
      resources :servers do
        collection do
          post :command
        end
      end
      resources :games
    end
  end
  resources :servers do
    collection do
      get :admin
      post :command
    end
    member do
      get :delete
    end
  end
  resources :games do
    collection do
      get :admin
      post :command
    end
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/server.rb
class Server < ApplicationRecord
  # id
  # friendly_name
  # ip
  # username
  # keyfile
  require_dependency 'ssh'
  require_dependency 'local_commands'

  has_many :games

  def connect
      @conn ||=SSH.new(self.ip, self.username, keys: [self.keyfile])
      @conn
  end

  def game_stats
    stats = {}
    stats[:num_running] = self.games.select { |g| g.running? }.size
    stats[:num_stopped] = self.games.select { |g| !g.running? }.size
    stats
  end

  def online?
    self.connect.online?
  end

  def uptime
    self.connect.system_uptime
  end

  def act_locally
    @alocal = ActLocally.new(self.ip, self.friendly_name)
    @alocal
  end
end

app/controllers/api/v0/servers_controller.rb
class Api::V0::ServersController < ApplicationController

  #This is the servers controller (API version) and can list servers and their associated games as well as edit the server information and make calls to these servers. Calls outlined below
  #For more info on games specific info and actions, check out games_controller.rb
  #This controller interacts with no views (API only) and touches the server and game db through their associated models
  #I'm keeping some test API calls in the Test API postman collection

  #Currently this controller can only handle 4 types of commands to the game servers.
  #-call_start - provided a valid game_id this tells the game and server models to call the SSH class in lib/ssh.rb to ssh into the Games server and use runit to start the relevant game server
  #-call_stop - provided a valid game_id this tells the game and server models to call the SSH class in lib/ssh.rb to ssh into the Games server and use runit to stop the relevant game server
  #-call_save - provided a valid game_id this tells the game and server models to call the ActLocally class in lib/local_commands.rb to send a preformatted rcon command with scripts/rcon
  #-get_last_saved_at - provided a valid game_id this tells the game and server models to call the ActLocally class in lib/local_commands.rb to run File.mtime on the game's .ark save on the nas

  VALID_COMMANDS = ["call_start","call_stop","call_save","get_last_saved_at"]

  #I don't know what this does

  skip_before_action :verify_authenticity_token

  #This seems like a best practice thing to tell the API controller to accept json but I'm not sure if it's necessary

  respond_to? :json

  #Below are the actions you can take on this controller (via the API).

  #GET - https://luricidex.com/api/v0/servers

  def index #GET
    render json: Server.all
  end

  def show #GET
    server = Server.find(params[:id])
    render json: server, status: 200
  end

  #POST - https://luricidex.com/api/v0/servers/command?id=6&game_id=14&command=call_save

  def command #POST
    server = Server.find(params[:id])
    game_id = params[:game_id] rescue nil
	  command = params[:command] rescue nil
	  game = Game.find(game_id)
	  game.send(command)
    if command == "call_start"
      sleep 3
      status = game.running?
      if status == true
        render json: "Server is starting", status: 200
      else
        render json: "Server failed to start", status:504
      end
    elsif command == "call_stop"
      sleep 20
      status = game.running?
      if status == false
        render json: "Server is stopped", status: 200
      else
        render json: "Server failed to stop", status:504
      end
    elsif command == "call_save"
      sleep 25
      updated = game.get_last_saved_at
      if updated == "Multiple saves found, something is probably wrong."
        render json: "Multiple saves found, something is probably wrong.", status: 500
      elsif updated != nil
        render json: "This map was last updated at #{updated}", status: 200
      else
        render json: "Something went wrong getting the updated time of this map", status:500
      end
    elsif command == "get_last_saved_at"
      updated = game.get_last_saved_at
      if updated == "Multiple saves found, something is probably wrong."
        render json: "Multiple saves found, something is probably wrong.", status: 500
      elsif updated != nil
        render json: "This map was last updated at #{updated}", status: 200
      else
        render json: "Something went wrong getting the updated time of this map", status:500
      end
    else
      render json: "There was an error with your request", status: 400
    end
  end

  def destroy #PATCH
    server = Server.find(params[:id])
    server.destroy
    render json: "Successfully destroyed", status: 204
  end

  def update #PUT
    server = Server.find(params[:id])
    server.update_attributes(server_params)
    render json: server, status: 200
  end

  def create #POST
    server = Server.new(server_params)
    server.save
    render json: server, status: 201
  end

  private

  #These are the only params allowed when sending an API request to the controller

  def server_params
    params.permit(:friendly_name, :ip, :username, :keyfile)
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  VALID_COMMANDS = ["call_start","call_stop","call_save"]

  layout 'admin_area'

  def index #GET
    @server = Server.all
  end

  def admin
    @server = Server.all
  end

  def command #POST
    game_id = params[:game_id] rescue nil
	  command = params[:command] rescue nil
	  @game = Game.find(game_id)
	  redirect_to('/servers') unless VALID_COMMANDS.include?(command)
	  @game.send(command)
    if command == "call_start"
      sleep 3
      redirect_to('/servers')
    elsif command == "call_stop"
      sleep 20
      redirect_to('/servers')
    elsif command == "call_save"
      sleep 15
      redirect_to('/servers')
    else
	    redirect_to('/servers')
    end
  end

  def delete
    @server = Server.find(params[:id])
  end

  def destroy
    @server = Server.find(params[:id])
    @server.destroy
    flash[:notice] = "Server '#{@server.friendly_name}' destroyed successfully."
    redirect_to('/servers/admin')
  end

  def edit
    @server = Server.find(params[:id])
  end

  def update
    @server = Server.find(params[:id])
    if @server.update_attributes(server_params)
      flash[:notice] = "Server updated successfully."
      redirect_to('/servers/admin')
    else
      render('new')
    end
  end

  def new
    @server = Server.new({:keyfile => '"/home/Web/.ssh/id_rsa"'})
  end

  def create
    @server = Server.new(server_params)
    if @server.save
      flash[:notice] = "Server created successfully."
      redirect_to('/servers/admin')
    else
      flash[:error] = "Server failed to be created."
      render('new')
    end
  end

  def show
    @server = Server.find(params[:id])
  end

  private

  def server_params
    params.require(:server).permit(:friendly_name, :ip, :username, :keyfile)
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<table summary="Server form fields">
  <tr>
    <th>Friendly Name</th>
    <td><%= f.text_field(:friendly_name) %></td>
  </tr>
  <tr>
    <th>IP</th>
    <td><%= f.text_field(:ip) %></td>
  </tr>
  <tr>
    <th>Username</th>
    <td><%= f.text_field(:username) %></td>
  </tr>
  <tr>
    <th>keyfile</th>
    <td><%= f.text_field(:keyfile) %></td>
  </tr>
</table>

app/views/servers/admin.html.erb
<% @page_title = "Server Admin" %>

<div class="servers index">
  <h2>Servers</h2>

  <%= link_to("Add New Server", new_server_path, :class => 'action new') %>

  <table class="listing" summary="subject list">
    <tr class="header">
      <th>#</th>
      <th>Friendly Name</th>
      <th>IP</th>
      <th>Username</th>
      <th>Keyfile</th>
      <th>Actions</th>
    </tr>
    <% @server.each do |server| %>
    <tr>
      <td><%= server.id %></td>
      <td><%= server.friendly_name %></td>
      <td><%= server.ip %></td>
      <td><%= server.username %></td>
      <td><%= server.keyfile %></td>
      <td>
        <%= link_to("Show", server_path(server), :class => 'action show') %>
        <%= link_to("Edit", edit_server_path(server), :class => 'action edit') %>
        <%= link_to("Delete", delete_server_path(server), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/servers/delete.html.erb
<% @page_title = "Remove Server" %>

<%= link_to("<< Back to List", '/servers/admin', :class => 'back link') %>

<div class="servers edit">
  <h2>Delete Server #<%= @server.id%></h2>

  <%= form_for(@server, :method => 'delete') do |f| %>

  <p>Are you sure you want to permanently delete this Server?</p>

  <p class="reference-name"><%= f.object.friendly_name %></p>

  <div class="form-buttons">
    <%= f.submit("Delete Server") %>
  </div>

  <% end %>
</div>

app/views/servers/edit.html.erb
<% @page_title = "Edit Server" %>

<%= link_to("<< Back to List", '/servers/admin', :class => 'back link') %>

<div class="servers edit">
  <h2>Edit Server #<%= @server.id%></h2>

  <%= form_for(@server) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>

  <div class="form-buttons">
    <%= f.submit("Edit Server") %>
  </div>
  <% end %>
</div>

app/views/servers/index.html.erb
<style>
.inline-button {
  display: flex;
  flex-flow: row wrap;
}

.inline-button input[type=submit] {
  margin-top: 16px;
  margin-right: 8px;
}

.inline-button * {
  margin-bottom: 2px;
}

.server-details p {
  margin-top: 2px;
  margin-bottom: 2px;
  margin-left: 55px;
}

.alert {
  color: #D41111;
}

.running {
  color: #018903;
}
</style>

<title>Luricidex</title>
<h1>Site Under Constrution</h1>
<p>Your patience please</p>

<% @server.each do |server| %>
<ul>
  <li>
    <b><%= server.friendly_name %></b>:
    <% if server.online? %>
      <%= server.game_stats[:num_running] %> games running,
      <%= server.game_stats[:num_stopped] %> games stopped,
      up for <%= distance_of_time_in_words(server.uptime) %>
      <ul>
        <% server.games.each do |game| %>
        <li>
            <% if game.running? %>
              <div class="inline-button">
                <%= button_to "Stop!", { :action => 'command' }, {:params => {:game_id => game.id, :command => "call_stop" }} %>
                <p><b class="running"><%= game.friendly_name %></b>: Up for <%= distance_of_time_in_words(game.uptime) %> (<%= game.uptime %> seconds)</p>
              </div>
              <div class="server-details">
                <p><i><%= game.notes %></i></p>
              </div>
              <div class="inline-button">
                <%= button_to "Save!", { :action => 'command' }, {:params => {:game_id => game.id, :command => "call_save" }} %>
                <p> This map was last updated at <%= game.get_last_saved_at %></p>
              </div>
            <% else %>
              <div class="inline-button">
                <%= button_to "Start!", { :action => 'command' }, {:params => {:game_id => game.id, :command => "call_start" }} %>
                <p><b><%= game.friendly_name %></b>: Down for <%= distance_of_time_in_words(game.uptime) %> (<%= game.uptime %> seconds)</p>
              </div>
              <div class="server-details">
                <p><i><%= game.notes %></i></p>
              </div>
            <% end %>
        </li>
        <% end %>
      </ul>
    <% else %>
      <i class="alert">Offline</i>
    <% end %>
  </li>
</ul>
<% end %>

app/views/servers/new.html.erb
<% @page_title = "Add Server" %>

<%= link_to("<< Back to List", '/servers/admin', :class => 'back link') %>

<div class="servers new">
  <h2>Create Server</h2>

  <%= form_for(@server) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>

  <div class="form-buttons">
    <%= f.submit("Create Server") %>
  </div>
  <% end %>
</div>

app/views/servers/show.html.erb
<% @page_title = "Show Server" %>

<%= link_to("<<Back to List", '/servers/admin', :class => 'back_link') %>

  <div class="servers show">
    <h2>Show Subject</h2>

    <table summary="Server detail view">
      <tr>
        <th>Name</th>
        <td><%= @server.friendly_name %></td>
      </tr>
      <tr>
        <th>IP</th>
        <td><%= @server.ip %></td>
      </tr>
      <tr>
        <th>Username</th>
        <td><%= @server.username %></td>
      </tr>
      <tr>
        <th>Keyfile</th>
        <td><%= @server.keyfile %></td>
      </tr>
      <tr>
        <th>Created</th>
        <td><%= @server.created_at %></td>
      </tr>
      <tr>
        <th>Updated</th>
        <td><%= @server.updated_at %></td>
      </tr>
    </table>

  </div>