config/routes.rb
Rails.application.routes.draw do
  root to: 'root#index'
  resources :root
  namespace :api do
    namespace :v0 do
      resources :servers do
        collection do
          post :command
        end
      end
      resources :games
    end
  end
  resources :servers do
    collection do
      get :admin
      post :command
    end
    member do
      get :delete
    end
  end
  resources :games do
    collection do
      get :admin
      post :command
    end
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  # id
  # server_id
  # friendly_name
  # service_name
  # port
  # notes

  belongs_to :server
  has_many :scheduled_stops

  def get_status
    @status ||= self.server.connect.status(self.service_name)
    @status
  end

  def running?
    get_status.running?
  end

  def uptime
    get_status.uptime
  end

  def call_start
	self.server.connect.start(self.service_name)
  end

  def call_stop
	self.server.connect.stop(self.service_name)
  end

  def call_save
	self.server.act_locally.save(self.server.ip, self.port)
  self.server.act_locally.last_saved_at(self.server.friendly_name, self.friendly_name)
  end

  def get_last_saved_at
	self.server.act_locally.last_saved_at(self.server.friendly_name.downcase, self.friendly_name.downcase)
  end
end

app/controllers/api/v0/games_controller.rb
class Api::V0::GamesController < ApplicationController
  skip_before_action :verify_authenticity_token
  respond_to? :json

  def index #GET
    render json: Game.all
  end

  def show #GET
    game = Game.find(params[:id])
    render json: game, status: 200
  end

  def destroy #PATCH
    game = Game.find(params[:id])
    game.destroy
    render json: "Successfully destroyed", status: 204
  end

  def update #PUT
    game = Game.find(params[:id])
    game.update_attributes(game_params)
    render json: game, status: 200
  end

  def create #POST
    game = Game.new(game_params)
    game.save
    render json: game, status: 201
  end

  private

  def game_params
    params.permit(:server_id, :friendly_name, :service_name, :port, :notes)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  layout 'admin_area'

  def admin
    @game = Game.all
  end

  def delete
    @game = Game.find(params[:id])
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    flash[:notice] = "Game '#{@game.friendly_name}' destroyed successfully."
    redirect_to('/games/admin')
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update_attributes(game_params)
      flash[:notice] = "Game updated successfully."
      redirect_to('/games/admin')
    else
      render('new')
    end
  end

  def new
    @game = Game.new({:server_id => 'input the SERVER id'})
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:notice] = "Game created successfully."
      redirect_to('/games/admin')
    else
      flash[:error] = "Game failed to be created."
      render('new')
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  private

  def game_params
    params.require(:game).permit(:server_id, :friendly_name, :service_name, :port, :notes)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<table summary="Server form fields">
  <tr>
    <th>Server</th>
    <td><%= f.text_field(:server_id) %></td>
  </tr>
  <tr>
    <th>Friendly Name</th>
    <td><%= f.text_field(:friendly_name) %></td>
  </tr>
  <tr>
    <th>Service Name</th>
    <td><%= f.text_field(:service_name) %></td>
  </tr>
  <tr>
    <th>RCON Port</th>
    <td><%= f.text_field(:port) %></td>
  </tr>
  <tr>
    <th>Notes</th>
    <td><%= f.text_field(:notes) %></td>
  </tr>
</table>

app/views/games/admin.html.erb
<% @page_title = "Game Admin" %>

<div class="games index">
  <h2>Games</h2>

  <%= link_to("Add New Game", new_game_path, :class => 'action new') %>

  <table class="listing" summary="subject list">
    <tr class="header">
      <th>#</th>
      <th>Server</th>
      <th>Friendly Name</th>
      <th>Service Name</th>
      <th>port</th>
      <th>Notes</th>
      <th>Actions</th>
    </tr>
    <% @game.each do |game| %>
    <tr>
      <td><%= game.id %></td>
      <td><%= game.server_id %></td>
      <td><%= game.friendly_name %></td>
      <td><%= game.service_name %></td>
      <td><%= game.port %></td>
      <td><%= game.notes %></td>
      <td>
        <%= link_to("Show", game_path(game), :class => 'action show') %>
        <%= link_to("Edit", edit_game_path(game), :class => 'action edit') %>
        <%= link_to("Delete", delete_game_path(game), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/games/delete.html.erb
<% @page_title = "Remove Game" %>

<%= link_to("<< Back to List", '/games/admin', :class => 'back link') %>

<div class="games edit">
  <h2>Delete Game #<%= @game.id%></h2>

  <%= form_for(@game, :method => 'delete') do |f| %>

  <p>Are you sure you want to permanently delete this Game?</p>

  <p class="reference-name"><%= f.object.friendly_name %></p>

  <div class="form-buttons">
    <%= f.submit("Delete Game") %>
  </div>

  <% end %>
</div>

app/views/games/edit.html.erb
<% @page_title = "Edit Game" %>

<%= link_to("<< Back to List", '/games/admin', :class => 'back link') %>

<div class="games edit">
  <h2>Edit Game #<%= @game.id%></h2>

  <%= form_for(@game) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>

  <div class="form-buttons">
    <%= f.submit("Edit Game") %>
  </div>
  <% end %>
</div>

app/views/games/index.html.erb
<title>Luricidex</title>
<h1>Site Under Constrution</h1>
<p>Did you mean:</p>
<%= link_to("Games Admin", "admin/") %>

app/views/games/new.html.erb
<% @page_title = "Add Game" %>

<%= link_to("<< Back to List", '/games/admin', :class => 'back link') %>

<div class="games new">
  <h2>Create Game</h2>

  <%= form_for(@game) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>

  <div class="form-buttons">
    <%= f.submit("Create Game") %>
  </div>
  <% end %>
</div>

app/views/games/show.html.erb
<% @page_title = "Show Game" %>

<%= link_to("<<Back to List", '/games/admin', :class => 'back_link') %>

  <div class="games show">
    <h2>Show Subject</h2>

    <table summary="Game detail view">
      <tr>
        <th>Server</th>
        <td><%= @game.server_id %></td>
      </tr>
      <tr>
        <th>Name</th>
        <td><%= @game.friendly_name %></td>
      </tr>
      <tr>
        <th>Service Name</th>
        <td><%= @game.service_name %></td>
      </tr>
      <tr>
        <th>Created</th>
        <td><%= @game.created_at %></td>
      </tr>
      <tr>
        <th>Updated</th>
        <td><%= @game.updated_at %></td>
      </tr>
    </table>

  </div>